# Generated by Django 4.1 on 2023-10-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="tb_user_chat",
            fields=[
                ("chat_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_nickname", models.CharField(default="", max_length=200)),
                ("chat_body", models.CharField(default="", max_length=2000)),
                ("chat_time", models.IntegerField(default=0)),
                ("db_time", models.IntegerField(default=0)),
                ("delete_status", models.IntegerField(default=0)),
            ],
        ),
    ]
